import { open } from './lib.mjs';
const w = Number(process.argv[2] || 1440), h = Number(process.argv[3] || 900);
const { browser, page } = await open(w, h);
await page.goto('https://www.kerra.earth/', { waitUntil: 'load', timeout: 90000 });
await page.waitForTimeout(5000);
const r = await page.evaluate(() => {
  const vis = (e) => e && e.getBoundingClientRect().width > 0;
  const q = (s) => [...document.querySelectorAll(s)].find(vis);
  const box = (e) => { if (!e) return null; const r = e.getBoundingClientRect(); const cs = getComputedStyle(e); return `${e.tagName.toLowerCase()}[${e.getAttribute('data-framer-name') || ''}] ${Math.round(r.left)},${Math.round(r.top + scrollY)} ${Math.round(r.width)}x${Math.round(r.height)} bg:${cs.backgroundColor} bgi:${cs.backgroundImage.slice(0, 120)} r:${cs.borderRadius} op:${cs.opacity} pad:${cs.padding} border:${cs.borderTopWidth} ${cs.borderTopColor} shadow:${cs.boxShadow} pos:${cs.position} z:${cs.zIndex} bdf:${cs.backdropFilter}`; };
  const out = {};
  const nav = [...document.querySelectorAll('nav')].find(vis);
  out.navChain = [nav, nav.parentElement, nav.parentElement.parentElement, ...nav.children].map(box);
  const nf = q('[data-framer-name="Name Field"]');
  out.field = [nf, ...nf.querySelectorAll('*')].map(box);
  const ta = q('[data-framer-name="Message Field"]');
  out.textarea = [ta, ...ta.querySelectorAll('*')].map(box);
  const tl = q('[data-framer-name="Hero"] [data-framer-name="top-left"]');
  const svg = tl && tl.querySelector('svg');
  out.bracket = { box: box(tl), svg: svg && svg.outerHTML.slice(0, 600) };
  const logo = q('[data-framer-name="MARKETS"] [data-framer-name="LOGO"]');
  out.wheelLogo = logo && [logo, ...logo.querySelectorAll('*')].slice(0, 4).map(box);
  out.marketsFades = [...document.querySelectorAll('[data-framer-name="MARKETS"] [data-framer-name^="fade"]')].filter(vis).map(box);
  const img = q('[data-framer-name="TECHNOLOGY"] [data-framer-name="image"]');
  out.techImage = img && [img, ...img.children].map(box);
  out.frame = [...document.querySelectorAll('[data-framer-name="FRAME"] > *')].map(box);
  out.desc = box(q('[data-framer-name="DESCRIPTION"]'));
  out.headline = box(q('[data-framer-name="Blind Reveal Headline"]'));
  out.contentL = box(q('[data-framer-name="Content L"]'));
  out.statCard = box(q('[data-framer-name="WHY"] [data-framer-name="Variant 1"]'));
  out.footerDot = box(q('[data-framer-name="FOOTER"] [data-framer-name="links"] svg'));
  out.social = box(q('[data-framer-name="linkedin"]'));
  out.pixel = box(q('[data-framer-name="Pixel Mask Reveal"]'));
  out.sectionGradient = box(q('[data-framer-name="WHY KERRA"] > [data-framer-name="gradient"]'));
  out.contactShader = [box(q('[data-framer-name="CONTACT"] [data-framer-name="shader"]')), box(q('[data-framer-name="Gradient Background"]'))];
  out.statText = [...document.querySelectorAll('[data-framer-name="WHY"] [data-framer-name="Stat Label"] p')].filter(vis).map(p => getComputedStyle(p).textAlign);
  out.introAlign = [...document.querySelectorAll('[data-framer-name="Content S"] h2, [data-framer-name="Content S"] p')].filter(vis).map(p => getComputedStyle(p).textAlign);
  return out;
});
console.log(JSON.stringify(r, null, 1));
await browser.close();
